= Notizen zu _Master Boot Record_
//===============================

:!compat-mode:

// METADATA ####################################################################
:author:    fresal
:date: 			2019-11-14
:version:   v0.1
// #############################################################################

// LINKS ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-
:Real-Mode: link:https://en.wikipedia.org/wiki/Real_mode[Real-Mode]
:BIOS: link:https://en.wikipedia.org/wiki/BIOS[BIOS]
:Bootloader: link:https://en.wikipedia.org/wiki/Booting#Modern_boot_loaders[Bootloader]
:Chainloading: link:https://en.wikipedia.org/wiki/Chain_loading[Chainloading]
:Partitions-Tabelle: link:https://en.wikipedia.org/wiki/Partition_table[Partitions-Tabelle]
:LBA: link:https://en.wikipedia.org/wiki/Logical_block_addressing[LBA]
:Boot_Configuration_Data: link:https://en.wikipedia.org/wiki/Windows_NT_6_startup_process#Boot_Configuration_Data[Boot Configuration Data (BCD)]
:fdisk: link:https://en.wikipedia.org/wiki/Fdisk[fdisk(1)]
// ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-



Der _Master Boot Record (MBR)_ ist die Bezeichnung für den ersten Sektor auf
dem Festspeicher (bei einem System das mittels _MBR_ bootet). +
Der *<<Aufbau eines Master Boot Records>>* besteht einerseits aus einen Bereich
mit _Bootstrap-Code_, der durch ein {BIOS} oder andere {Bootloader} ausgeführt
wird und seinerseits weiteren Code nachlädt. +
Andererseits enthält er eine *<<Partitions-Tabelle>>* für das
Festspeichermedium.

Wegen der maximalen 32-bit Breite der
*_<<LBA-Block-Adressen,LBA-Block-Adressen>>_* in der
Partitions-Tabelle beträgt die maximal adressierbare Grösse eines
Speichermediums: `2 TiB` +

--------------------------------------------------------------------------------
32-bit–Adressraum * Blockgrösse =
2^32              * 512 Bytes   = 2^32 * 2^9 = 2^41 = 2 TiB
--------------------------------------------------------------------------------

Diese Limitierung war der Hauptgrund für die Einführung der _GUID Partition
Table (GPT)_. In den meisten Systemen ist heutzutage der MBR durch die GPT
abgelöst worden. Aber auch in GPT spielt der MBR aus Kompatibliätsgründen als
sogenannter *_<<Protective MBR>>_* eine Rolle.
// %%%% Link auf GPT Doku einfügen.

_In diesem Dokument werden nur die allgemeingültigen und "`modernen`"
Eigenschaften von Master Boot Record behandelt (d.h. seit der Einführung von
*<<LBA - Logical Block Addressing>>* in 1996)._




[[warnung]]
== Generelle Warnung

_Wegen der historischen verworrenen Entwicklung des MBR gibt es trotz Standards
scheinbar für jede Regel abweichende Varianten mit zuweilen subtilen
Unterschieden._

*_Wegen dieser vielen irrationalen oder schwer nachzuvollziehenden Details ist
dringend zu empfehlen das Berechnen und Setzen von Werten im MBR im Normalfall
einem Partition-Tool wie {fdisk} zu überlassen._*
// %%%% Link auf LBA einfügen
// %%%% Ev. Link auf Dokument zur Illustration der subtilen Unterschiede




== Hilfe und Dokumentation

_[noch nichts]_




== Aufbau eines Master Boot Records

// LINKS ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-
:Endianness: link:https://en.wikipedia.org/wiki/Endianness[Endianness]
:grosse_Unterschiede: link:https://en.wikipedia.org/wiki/Master_boot_record#Sector_layout[grosse Unterschiede]
// ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-



=== MBR ist _little endian_

Weil {Real-Mode} Code _little-endian_ ist, ist auch MBR _little-endian_.

Als Errinnerung: {Endianness} bezeichnet die *Byte-Reihenfolge* von Zahlen:

* Bei *_big-endian_* sind in *tieferen* Speicher-Adressen *signifikantere*
  Bytes.
* Bei *_little-endian_* sind in *tieferen* Speicher-Adressen *weniger
  signifikate* Bytes.

.Beispiel für Endianness
--------------------------------------------------------------------------------

        Big-Endian                               Little-Endian
       __ __ __ __                                 __ __ __ __
  addr  0  1  2  3                            addr  0  1  2  3
| 000  a1 b2 c3 d4   <--- 0x a1b2c3d4 --->  | 000  d4 c3 b2 a1

   "This is sane."                                 "Pathetic!"

--------------------------------------------------------------------------------



=== MBR Block Layout


Ein gesamter _MBR_-Block besteht aus 512 Bytes (d.h. Standard-Sektor-Grösse).

Der grösste Teil davon ist der _{Real-Mode} Bootstrap Code_. Der Bereich
von `0x000` bis und mit `0x1BD` kann je nach _MBR_-Variante
{grosse_Unterschiede} aufweisen (vor allem bei _MBRs_ älter als 1996).

Manchmal endet der Code Bereich in einer 6-Byte langen _Disk Signature_, die
für Windows Systeme wichtig ist, um Partitionen konsistent den gleichen
Laufwerks-Buchstaben zuzuordnen. Ausserdem ist die _Disk Signature_ seit
Windows Vista in den sogenannten _{Boot_Configuration_Data}_ eingetragen.
Wenn die Signaturen in _MBR_ und _BCD_ nicht mehr übereinstimmen, kann Windows
nicht mehr booten.

[[Partitions-Tabelle,Partitions-Tabelle]]
Die {Partitions-Tabelle} beginnt an Adresse `0x1BE` und besteht aus 4 Einträgen
zu je 16 Byte.

Die letzten 2 Bytes sind die *Boot Signature*, die immer `55` `AA` lautet. +
[.small]#Achtung Endianess ! In Software lautet der Wert `0xAA55` !#


==== Layout eines MBR Blocks

--------------------------------------------------------------------------------
       __ __ __ __ __ __ __ __  __ __ __ __ __ __ __ __   ________________  ___
  addr  0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F   Byte Typen          #
| 000  // // // // // // // //  // // // // // // // //
| 010  // // // // // // // //  // // // // // // // //
| 020  // // // // // // // //  // // // // // // // //   // Real-Mode   =< 446
| 030  // // // // // // // //  // // // // // // // //      Bootstrap
| 040  // //             // //  // //             // //      Code
| 050  // //    // // // // //  // //    // //    // //
| 060  // //    // // // // //  // //    // //    // //
| 070  // //    // // // // //  // //    // //    // //
| 080  // //    // // // // //  // //    // //    // //
| 090  // //    // // // // //  // //    // //    // //
| 0a0  // //             // //  // //             // //
| 0b0  // // // // // // // //  // // // // // // // //
| 0c0  // // // // // // // //  // // // // // // // //
| 0d0  // //          // // //  // //             // //
| 0e0  // //    // //    // //  // //    // // // // //
| 0f0  // //    // //    // //  // //    // // // // //
| 100  // //    // //    // //  // //          // // //
| 110  // //    // //    // //  // //    // // // // //
| 120  // //    // //    // //  // //    // // // // //
| 130  // //          // // //  // //             // //
| 140  // // // // // // // //  // // // // // // // //
| 150  // // // // // // // //  // // // // // // // //
| 160  // // // // // // // //  // // // // // // // //
| 170  // // // // // // // //  // // // // // // // //   $$ Disk Signature  [6]
| 180  // // // // // // // //  // // // // // // // //      endet in 00 00
| 190  // // // // // // // //  // // // // // // // //      oder     5A 5A
| 1a0  // // // // // // // //  // // // // // // // //
| 1b0  // // // // // // // //  $$ $$ $$ $$ 00 00 ** **   ** Partition 1     16
| 1c0  ** ** ** ** ** ** ** **  ** ** ** ** ** ** ?? ??   ?? Partition 2     16
| 1d0  ?? ?? ?? ?? ?? ?? ?? ??  ?? ?? ?? ?? ?? ?? .. ..   .. Partition 3     16
| 1e0  .. .. .. .. .. .. .. ..  .. .. .. .. .. .. @@ @@   @@ Partition 4     16
| 1f0  @@ @@ @@ @@ @@ @@ @@ @@  @@ @@ @@ @@ @@ @@ 55 AA
                                                 '-----'
                                                    |
                                                    Boot Signature            2
                                                    ist immer 55 AA

--------------------------------------------------------------------------------


[[partition-entry]]
==== Layout eines Partition-Eintrags
--------------------------------------------------------------------------------
       __ __ __ __ __ __ __ __  __ __ __ __ __ __ __ __
  addr  0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
| 1b0                                             PS ((
| 1c0  (( (( PT )) )) )) @@ @@  @@ @@ ## ## ## ##


    ______________________  ___
    Byte-Typen                #

    PS  Partition Status      1
    ((  Erste CHS-Addresse    3  -----.-----  Jede CHS-Adresse besteht aus:
    PT  Partition Type        1      /        1. Byte: Head-Bits    :  7 bis 0
    ))  Letzte CHS-Adresse    3  ---'         2. Byte: Cylinder-Bits:  7 bis 6
    @@  Erste LBA-Addresse    4                        Sector-Bits  :  5 bis 0
    ##  LBA Block-Anzahl      4               3. Byte: Cylinder-Bits:  7 bis 0

--------------------------------------------------------------------------------

// LINKS ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-
:MSB: link:https://en.wikipedia.org/wiki/Bit_numbering#Most_significant_bit[MSB]
:CHS: link:https://en.wikipedia.org/wiki/Cylinder-head-sector[CHS (Cylinder-head-sector)]
// ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-


==== Partition Status

Der 1-Byte lange _Partition Status_ gibt an, ob eine Partition *_active_* ist,
dh. ob sie die Partition ist, von der gebootet wird. Nur eine der 4 Partitionen
darf als *_active_* markiert sein.

* _Partition Status_: `PS` = `80` bedeutet *_active_*
* _Partition Status_: `PS` = `00` bedeutet *_inactive_*

[.small]#Theoretisch wäre nur das {MSB} des _Partition Status_ entscheidend
aber in einigen _MBRs_ und _VBRs_ gelten Werte, die nicht `0x80 = 1000b` oder
`0x00 = 0000b` sind als ungültig. Siehe: <<warnung>>#


==== Partition Type

Der 1-Byte lange _Partition Type_ bzw. die _Partition ID_ gibt an, _was_ sich in
der Partition befindet. +
Es ist dem Betriebssystem überlassen, wie es den _Partition Type_ interpretiert.

* _Partition Type_: `PT` = ein Byte-Wert

Grosse Tabelle aller möglichen _Partition Types_: +
link:https://en.wikipedia.org/wiki/Partition_type#List_of_partition_IDs[https://en.wikipedia.org/wiki/Partition_type#List_of_partition_IDs]

Spezielle _Partition Types_, die man aus dem Stegreif erkennen können sollte:

[cols='1,1,4']
|===============================================================================
| Partition Type | Typ        | Beschreibung
| `00`           | Free       | Leerer Partitionseintrag
| `EE`           | Blocker    | GPT protective MBR
| `EF`           | Service FS
  | EFI system partition (FAT12, FAT16, FAT32, oder anderes FS)
|===============================================================================

// %%%%Verweise auf EFI und GPT setzen


==== CHS - Cylinder Head Sector

Mit den zweimal 3-Byte langen _CHS-Adressen_ wird beschrieben, _wo_ auf dem
Speichermedium eine Partition beginnt und wo sie endet.

* Erste CHS-Adresse der Partition: `(( (( ((` = 3 Byte-Werte
* Letzte CHS-Adresse der Partition: `)) )) ))` = 3 Byte-Werte

Innerer Aufbau der CHS-Adressen: siehe <<partition-entry>>.

Die Berechnung von korrekten CHS-Adressen ist einer der undurchsichtigsten
Aspekte von _MBR_. Es sei hier ausdrücklich auf die <<warnung>> verwiesen.

[.small]#Ursprünglich entsprach {CHS} der physichen Geometrie der
Festplatte. Aber bereits seit den 80er Jahren wird die _CHS-Adressierung_ von
Festplatten-Controllern abstrahiert. Neben _CHS_ gibt es seit 1996 eine
modernere Variante, die per Definition abstrakt ist: <<LBA - Logical Block Addressing>>.#

[.small]#Weil _CHS_ historisch zuerst da war, muss es theoretisch immer
zusätzlich zu _LBA_ definiert werden, dies aus Kompatibilitätsgründen. Für
Partitionen die grösser als der CHS-Adressraum `pass:[24 bit @ 512 Byte]` =
`pass:[2^24 * 2^9]` = `pass:[2^33]` = `pass:[8 GiB]` sind, wird per Konvention
die höchste mögliche CHS-Addresse `1023 254 63` eingetragen. Entgegen der
Theorie ist es aber erfahrungsgemäss egal welche Werte in den CHS-Feldern
stehen.#


[[LBA-Block-Adressen]]
==== LBA - Logical Block Addressing

Mit den zweimal 4-Byte langen _LBA-Adressen_ wird beschrieben, _wo_ auf dem
Speichermedium eine Partition beginnt und wieviele Sektoren sie umfasst.

`0x00000000 = 0` ist die tiefste Adresse. Zur höchsten Adresse `0xFFFFFFFF = 4'294'967'295` wird schlicht Sektor um Sektor hochgezählt.

* _LBA-Adresse_ des ersten Sektors der Partition: `@@ @@ @@ @@` = 4 Byte-Werte
* Anzahl Blöcke/Sektoren, die die Partition umfasst: `pass:[## ## ## ##]` = 4
  Byte-Werte

[.small]#Je nach _MBR_ müssen die Partitionsgrenzen auf Cylinder-Grenzen der
CHS-Adressierung zu liegen kommen. +
Siehe <<warnung>>#



=== Beispiel für einen MBR-Block

// LINKS ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-
:Legacy-BIOS-Mode: link:https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface#CSM_booting[CSM/Legacy-BIOS-Mode]
// ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-

Der gezeigte _MBR_ stammt von einem Windows 7 auf einem Rechner mit BIOS bzw.
{Legacy-BIOS-Mode}. Er besteht aus zwei Partitionen mit _Partition Type_ `07`
d.h. _NTFS_. Die erste kleinere Partition ist eine Service Partition, die als
*_active_* makiert ist, d.h. _MBR_ bootet in diese Partition.

--------------------------------------------------------------------------------
$ sudo fdisk /dev/disk0
Signature: 0xAA55
         Starting       Ending
 #: id  cyl  hd sec -  cyl  hd sec [     start -       size]
------------------------------------------------------------------------
*1: 07    0  32  33 -   12 223  19 [      2048 -     204800] HPFS/QNX/AUX
 2: 07   12 223  20 - 1023 254  63 [    206848 -   25935872] HPFS/QNX/AUX
 3: 00    0   0   0 -    0   0   0 [         0 -          0] unused
 4: 00    0   0   0 -    0   0   0 [         0 -          0] unused
--------------------------------------------------------------------------------

[source,shell]
--------------------------------------------------------------------------------
$ sudo dd if=/dev/disk0 count=1 | hexdump -Cv
00000000  33 c0 8e d0 bc 00 7c 8e  c0 8e d8 be 00 7c bf 00  |3.....|......|..|
00000010  06 b9 00 02 fc f3 a4 50  68 1c 06 cb fb b9 04 00  |.......Ph.......|
00000020  bd be 07 80 7e 00 00 7c  0b 0f 85 0e 01 83 c5 10  |....~..|........|
00000030  e2 f1 cd 18 88 56 00 55  c6 46 11 05 c6 46 10 00  |.....V.U.F...F..|
00000040  b4 41 bb aa 55 cd 13 5d  72 0f 81 fb 55 aa 75 09  |.A..U..]r...U.u.|
00000050  f7 c1 01 00 74 03 fe 46  10 66 60 80 7e 10 00 74  |....t..F.f`.~..t|
00000060  26 66 68 00 00 00 00 66  ff 76 08 68 00 00 68 00  |&fh....f.v.h..h.|
00000070  7c 68 01 00 68 10 00 b4  42 8a 56 00 8b f4 cd 13  ||h..h...B.V.....|
00000080  9f 83 c4 10 9e eb 14 b8  01 02 bb 00 7c 8a 56 00  |............|.V.|
00000090  8a 76 01 8a 4e 02 8a 6e  03 cd 13 66 61 73 1c fe  |.v..N..n...fas..|
000000a0  4e 11 75 0c 80 7e 00 80  0f 84 8a 00 b2 80 eb 84  |N.u..~..........|
000000b0  55 32 e4 8a 56 00 cd 13  5d eb 9e 81 3e fe 7d 55  |U2..V...]...>.}U|
000000c0  aa 75 6e ff 76 00 e8 8d  00 75 17 fa b0 d1 e6 64  |.un.v....u.....d|
000000d0  e8 83 00 b0 df e6 60 e8  7c 00 b0 ff e6 64 e8 75  |......`.|....d.u|
000000e0  00 fb b8 00 bb cd 1a 66  23 c0 75 3b 66 81 fb 54  |.......f#.u;f..T|
000000f0  43 50 41 75 32 81 f9 02  01 72 2c 66 68 07 bb 00  |CPAu2....r,fh...|
00000100  00 66 68 00 02 00 00 66  68 08 00 00 00 66 53 66  |.fh....fh....fSf|
00000110  53 66 55 66 68 00 00 00  00 66 68 00 7c 00 00 66  |SfUfh....fh.|..f|
00000120  61 68 00 00 07 cd 1a 5a  32 f6 ea 00 7c 00 00 cd  |ah.....Z2...|...|
00000130  18 a0 b7 07 eb 08 a0 b6  07 eb 03 a0 b5 07 32 e4  |..............2.|
00000140  05 00 07 8b f0 ac 3c 00  74 09 bb 07 00 b4 0e cd  |......<.t.......|
00000150  10 eb f2 f4 eb fd 2b c9  e4 64 eb 00 24 02 e0 f8  |......+..d..$...|
00000160  24 02 c3 49 6e 76 61 6c  69 64 20 70 61 72 74 69  |$..Invalid parti|
00000170  74 69 6f 6e 20 74 61 62  6c 65 00 45 72 72 6f 72  |tion table.Error|
00000180  20 6c 6f 61 64 69 6e 67  20 6f 70 65 72 61 74 69  | loading operati|
00000190  6e 67 20 73 79 73 74 65  6d 00 4d 69 73 73 69 6e  |ng system.Missin|
000001a0  67 20 6f 70 65 72 61 74  69 6e 67 20 73 79 73 74  |g operating syst|
000001b0  65 6d 00 00 00 63 7b 9a  e5 fe 65 be 00 00 80 20  |em...c{...e.... |
000001c0  21 00 07 df 13 0c 00 08  00 00 00 20 03 00 00 df  |!.......... ....|
000001d0  14 0c 07 fe ff ff 00 28  03 00 00 c0 8b 01 00 00  |.......(........|
000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
00000200

--------------------------------------------------------------------------------




== Spezielle _Master Boot Records_

Es gibt zwei spezielle _MBRs_, die im Zusammenhang mit
_GUID Partition Table (GPT)_ wichtig zu kennen sind:



=== Protective MBR

Ein _Protective MBR (PMBR)_ dient als Schutz vor dem Überschreiben von
_GUID Partition Tables (GPTs)_ durch Partition-Tools, die nur MBR kennen.
Jede GPT enthält einen _Protective MBR_.

// %%%%% Link auf GPT Doku setzen

Ein _Protective MBR_ hat einen ungewöhnlichen Aufbau: Die Partitionstabelle
enthält nur eine einzige *_inactive_* Partition vom _Partition-Type_ `ee`, die
das ganze Speichermedium umfasst bzw. die maximalen `2 TiB`, die MBR
unterstützt, falls das Speichermedium grösser ist. Ein _Protective MBR_ kann
{Real-Mode} Bootstrap Code enthalten, muss aber nicht.

==== Beispiel für ein Protective MBR

… einer Festplatte mit `pass:[~ 240 GiB]` bzw. `468862128 Sektoren`

[source,shell]
--------------------------------------------------------------------------------
$ sudo fdisk /dev/disk0
Disk: /dev/disk0  geometry: 29185/255/63 [468862128 sectors]
Signature: 0xAA55
         Starting       Ending
 #: id  cyl  hd sec -  cyl  hd sec [     start -       size]
------------------------------------------------------------------------
 1: EE 1023 254  63 - 1023 254  63 [         1 -  468862127] <Unknown ID>
 2: 00    0   0   0 -    0   0   0 [         0 -          0] unused
 3: 00    0   0   0 -    0   0   0 [         0 -          0] unused
 4: 00    0   0   0 -    0   0   0 [         0 -          0] unused
--------------------------------------------------------------------------------

[source,shell]
--------------------------------------------------------------------------------
$ sudo dd if=/dev/disk0 count=1 bs=512 | hexdump
0000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
00001b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00[00 fe
00001c0 ff ff ee fe ff ff 01 00 00 00 af 44 f2 1b]00 00
00001d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
00001f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 55 aa
0000200
--------------------------------------------------------------------------------
(Der Partitions-Eintrag wurde zusätzlich mit `[` und `]` markiert.)


=== Hybrid MBR

_pass:[[noch nichts]]_




== Andere _Boot Records_



=== Volume Boot Record (VBR)

// LINKS ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-
:FAT16: link:https://en.wikipedia.org/wiki/File_Allocation_Table#Initial_FAT16[FAT16]
:FAT32: link:https://en.wikipedia.org/wiki/File_Allocation_Table#FAT32[FAT32]
:NTFS: link:https://en.wikipedia.org/wiki/NTFS[NTFS]
:BIOS-Parameter-Block-BPB: link:https://en.wikipedia.org/wiki/BIOS_parameter_block[BIOS Parameter Block (BPB)]
// ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->-

Der _Volume Boot Record (VBR)_ ist die Bezeichnung für den ersten Sektor eines
unpartitionierten Speichermediums oder für den ersten Sektor einer Partition.

MBR und VBR  sind verwandt, gehören aber nicht zwingend zusammen. Ein System,
dass Master Boot Record benutzt, hat häufig Volume Boot Records in den
Partitionen. Das ist aber nicht immer der Fall. Analog gibt es Speichermedien,
die zwar Volume Boot Records haben aber keinen Master Boot Record.

Ähnlich wie ein MBR enthält ein VBR einen Bereich mit Bootstrap-Code sowie die
Boot-Signatur `55 AA` in den letzten zwei Bytes des Sektors. Ein VBR enthält
aber _keine_ Partitionstabelle.

Bei Dateisystemen wie {FAT16}, {FAT32} und {NTFS} enthält der VBR die
Informationen über Speicherort und Aufbau des Dateisystems als sogenannten
_{BIOS-Parameter-Block-BPB}_.


==== Beispiel für einen _Volume Boot Record_

… im Sektor `2048` einer {NTFS}-Partition, die mittels der Partitionstabelle
im Master Boot Record des Speichermediums gefunden wurde.

--------------------------------------------------------------------------------
$ sudo fdisk /dev/disk0
Disk: /dev/disk0  geometry: 14593/255/63 [234441648 sectors]
Signature: 0xAA55
         Starting       Ending
 #: id  cyl  hd sec -  cyl  hd sec [     start -       size]
------------------------------------------------------------------------
*1: 07    0  32  33 -   12 223  19 [      2048 -     204800] HPFS/QNX/AUX
 2: 07   12 223  20 - 1023 254  63 [    206848 -   25935872] HPFS/QNX/AUX
 3: 00    0   0   0 -    0   0   0 [         0 -          0] unused
 4: 00    0   0   0 -    0   0   0 [         0 -          0] unused

$ sudo dd if=/dev/disk0 skip=2048 count=1 | hexdump -Cv
00000000  eb 52 90 4e 54 46 53 20  20 20 20 00 02 08 00 00  |.R.NTFS    .....|
00000010  00 00 00 00 00 f8 00 00  3f 00 ff 00 00 08 00 00  |........?.......|
00000020  00 00 00 00 80 00 80 00  ff 1f 03 00 00 00 00 00  |................|
00000030  55 21 00 00 00 00 00 00  02 00 00 00 00 00 00 00  |U!..............|
00000040  f6 00 00 00 01 00 00 00  8e 12 6f 9c 2f 6f 9c 0c  |..........o./o..|
00000050  00 00 00 00 fa 33 c0 8e  d0 bc 00 7c fb 68 c0 07  |.....3.....|.h..|
00000060  1f 1e 68 66 00 cb 88 16  0e 00 66 81 3e 03 00 4e  |..hf......f.>..N|
00000070  54 46 53 75 15 b4 41 bb  aa 55 cd 13 72 0c 81 fb  |TFSu..A..U..r...|
00000080  55 aa 75 06 f7 c1 01 00  75 03 e9 dd 00 1e 83 ec  |U.u.....u.......|
00000090  18 68 1a 00 b4 48 8a 16  0e 00 8b f4 16 1f cd 13  |.h...H..........|
000000a0  9f 83 c4 18 9e 58 1f 72  e1 3b 06 0b 00 75 db a3  |.....X.r.;...u..|
000000b0  0f 00 c1 2e 0f 00 04 1e  5a 33 db b9 00 20 2b c8  |........Z3... +.|
000000c0  66 ff 06 11 00 03 16 0f  00 8e c2 ff 06 16 00 e8  |f...............|
000000d0  4b 00 2b c8 77 ef b8 00  bb cd 1a 66 23 c0 75 2d  |K.+.w......f#.u-|
000000e0  66 81 fb 54 43 50 41 75  24 81 f9 02 01 72 1e 16  |f..TCPAu$....r..|
000000f0  68 07 bb 16 68 70 0e 16  68 09 00 66 53 66 53 66  |h...hp..h..fSfSf|
00000100  55 16 16 16 68 b8 01 66  61 0e 07 cd 1a 33 c0 bf  |U...h..fa....3..|
00000110  28 10 b9 d8 0f fc f3 aa  e9 5f 01 90 90 66 60 1e  |(........_...f`.|
00000120  06 66 a1 11 00 66 03 06  1c 00 1e 66 68 00 00 00  |.f...f.....fh...|
00000130  00 66 50 06 53 68 01 00  68 10 00 b4 42 8a 16 0e  |.fP.Sh..h...B...|
00000140  00 16 1f 8b f4 cd 13 66  59 5b 5a 66 59 66 59 1f  |.......fY[ZfYfY.|
00000150  0f 82 16 00 66 ff 06 11  00 03 16 0f 00 8e c2 ff  |....f...........|
00000160  0e 16 00 75 bc 07 1f 66  61 c3 a0 f8 01 e8 09 00  |...u...fa.......|
00000170  a0 fb 01 e8 03 00 f4 eb  fd b4 01 8b f0 ac 3c 00  |..............<.|
00000180  74 09 b4 0e bb 07 00 cd  10 eb f2 c3 0d 0a 41 20  |t.............A |
00000190  64 69 73 6b 20 72 65 61  64 20 65 72 72 6f 72 20  |disk read error |
000001a0  6f 63 63 75 72 72 65 64  00 0d 0a 42 4f 4f 54 4d  |occurred...BOOTM|
000001b0  47 52 20 69 73 20 6d 69  73 73 69 6e 67 00 0d 0a  |GR is missing...|
000001c0  42 4f 4f 54 4d 47 52 20  69 73 20 63 6f 6d 70 72  |BOOTMGR is compr|
000001d0  65 73 73 65 64 00 0d 0a  50 72 65 73 73 20 43 74  |essed...Press Ct|
000001e0  72 6c 2b 41 6c 74 2b 44  65 6c 20 74 6f 20 72 65  |rl+Alt+Del to re|
000001f0  73 74 61 72 74 0d 0a 00  8c a9 be d6 00 00 55 aa  |start.........U.|
00000200
--------------------------------------------------------------------------------



=== Extended Boot Record (EBR)


// TODO %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
// * Erster Durchlauf: alle nützlichen Infos aus Wikipedia
// * Zweiter Durchlauf: Quellen nach weiterem nützlichen und Quellenangaben
//                      durchsuchen

// * Hybrid MBR zumindest erwähnen

// * Extended boot record
// * Boot Stages
// * Ev. einige nützliche Tool-Einsätze aufzählen
//   ** MBR reparieren
//
// * Folgenden Link verarbeiten: https://blog.andersonshatch.com/2009/01/11/windows-7-x64-on-a-macbook-pro-guide/
// %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''




// [bibliography]
// == Bibliographie

// // Bei allen Referenz-Snapshots sollte die Lizenz vermerkt sein.

// * [[[example,1]]] IEEE-Ref +
//   [.small]#(link:dir/file.pdf[Snapshot] / Lizenz: keine oder unbekannt / © #
